export const HELP_TEXT = {
  'Mobile AR app revenue forecast by app store': 'Forecast valuing the market for mobile AR apps developed for smartphone and tablet screens, segmented by app store (Apple App Store, Google Play, Other app stores).',
  'Mobile AR app revenue forecast by OS': 'Forecast valuing the market for mobile AR apps developed for smartphone and tablet screens, segmented by OS (iOS, Android, Other OS).',
  'Games console device forecast': 'Historical and forecast unit sales, installed base, active users, and household penetration of home game consoles (seventh generation onward), with installed base also split between internet-connected and nonconnected consoles.',
  'Ad-blocking forecast': 'Forecast and historical assessment of the economic impact of ad blockers on internet advertising revenues.',
  'Digital advertising forecast': 'Forecast and historical spending by advertisers on platforms accessed through an internet connection on nonmobile devices (i.e., desktop PCs, laptops) or via mobile devices (i.e., smartphones, tablets).',
  'Mobile messaging traffic and revenue forecast': 'Forecast and historical telco SMS and MMS traffic volumes for countries and regions split by A2P SMS and photo and video MMS traffic. Also includes total telco mobile messaging revenues.',
  '4K and connected TV devices': 'Forecasted installed base, unit sales and users for 4K and connected TV devices by country and devices.',
  'All core datasets': 'Historical and forecasted subscriptions and KPI for Mobile, Fixed Voice, Fixed Broadband, TV and OTT services',
  'Fixed broadband by speed': 'Forecasted fixed broadband subscriptions split by connection speed split by country',
  'Fixed broadband subscriptions': 'Historical and forecasted fixed broadband subscriptions by company and technology',
  'Fixed operator services': 'Forecast & historical subscriptions for fixed broadband & fixed voice services split by company & technology. Forecast & historical financial KPIs for fixed broadband & fixed voice services split by country & company.',
  'Mobile data subscriptions': 'Historical mobile data users split by company and billing type (prepaid & postpaid)',
  'Mobile devices': 'Forecast subscriptions for mobile services by device type (smartphone/non-smartphone/portable)',
  'Mobile device subscriptions': 'Forecast subscriptions for mobile services split by device type (smartphone/nonsmartphone/portable).',
  'Mobile M2M subscriptions': 'Forecasted and historical subscriptions for M2M mobile services by company and technology',
  'Mobile MVNO M2M subscriptions': 'Historical M2M subscriptions for MVNO services split by company and technology',
  'Mobile MVNO services': 'Historical subscriptions for MVNO services split by company, technology, and billing type (prepaid and postpaid).',
  'Mobile MVNO subscriptions excluding M2M': 'Historical Non M2M subscriptions for MVNO services split by company and technology',
  'Mobile MVNO subscriptions': 'Historical subscriptions for MVNO services split by company and technology',
  'Mobile network operator services': 'Forecast & historical subscriptions split by company and technology. Forecast & historical financial KPIs split by country, company, and service. Forecasted mobile unique users split by country and mobile device sales split by country and technology.',
  'Mobile subscriptions': 'Historical and forecasted mobile subscriptions by company and technology',
  'Mobile subscriptions excluding M2M': 'Historical and forecasted subscriptions for non M2M mobile services by company, technology and billing type (prepaid and postpaid)',
  'Other operator services': 'Historical financial KPIs split by company for services other than traditional fixed, mobile and TV services',
  'OTT SVOD subscriptions': 'Forecast SVOD subscriptions by country',
  'OTT services': 'Forecast SVOD subscriptions split by company. Forecast financial KPI for OTT services split by country, billing type and resolution',
  'OTT video services': 'Forecasted SVOD subscriptions by company. Forecasted SVOD, TVOD, and AVOD connections and financial KPIs by country, billing type, and resolution.',
  'Prepaid and Postpaid Mobile Subscriptions': 'Forecasted subscriptions for mobile services by country and billing type (prepaid and postpaid)',
  'Public service TV': 'Forecasted TV Licence revenues by country',
  'Tablet subscriptions': 'Forecast installed base for tablets by country.',
  'TV devices': 'Forecasted installed base, unit sales and users for TV services by country, device type and technology',
  'TV services': 'Forecast and historical subscriptions for TV services split by company and technology. Historical financial KPIs split by company. Forecast financial KPIs split by country, technology, and billing type. TV advertising revenues split by country.',
  'TV households': 'Forecast & historical households, penetration, and TV sets split by country, technology, device, and billing type.',
  'OTT messaging forecast': 'Forecast of the number of mobile and fixed registered users, monthly active users, and annual messaging traffic (text, picture, video) for eight regions and 67 countries.',
  'OTT VoIP forecast': 'Forecast and historical OTT VoIP minutes of use across mobile and fixed devices by country and region. The forecast also splits out international and domestic OTT VoIP minutes of use at a country level.',
  'Cellular device forecast': 'Forecast detailing end-user volume sales for cellular devices (handsets, data cards, dongles, WWAN-enabled tablets, netbooks, notebooks). Split by technology, 67 countries, and eight regions.',
  'eSIM device forecast': 'Forecast and historical unit sales for eSIM-compatible smartphones, tablets, wearables, and other portable devices. Forecasts are provided for major regional markets.',
  'Handset forecast by access technology': 'Forecast and historical mobile handset unit sales by access technology (2G, 3G, 4G, 5G) for 70 countries. Splits are provided by type of customer (consumer and corporate-liable).',
  'Handset forecast by OS': 'Forecast and historical unit sales, installed base, revenues, and ASP for mobile handsets by mobile OS (iOS, Android, other OS) for 70 countries. Splits are provided by type of customer (consumer & corporate-liable).',
  'Handset forecast by price': 'Forecast and historical mobile handset unit sales by price segment for 70 countries. Splits are provided by type of customer (consumer and corporate-liable).',
  'Set-top box forecast by platform': 'Forecast and historical unit sales and installed base for digital STBs. Splits are provided by TV platform (cable, IPTV, DTH, DTT), media streamers, and major regional and national markets.',
  'Smart home devices forecast': 'Forecast detailing smart home device penetration rates, installed base, and unit sales segmented by four different categories of devices (appliances, utilities, security, smart speakers) for 21 major markets.',
  'Tablet forecast by access technology': 'Forecast and historical tablet volume sales and installed base by access technology (Wi-Fi only, 3G, 4G+) for nine regions and 19 key countries.',
  'Tablet forecast by OS': 'Forecast and historical tablet volume sales and installed base by operating system (iOS, Android, Windows, other OS) for nine regions and 19 key countries.',
  'TV set forecast by technology': 'Forecast and historical unit sales, installed base, households, and users for 4K UHD TV sets. Splits are provided for major regional and national markets.',
  'TV set forecast by type': 'Forecast and historical unit sales, installed base, households, and users for TV sets. Splits are provided by device type (regular vs. smart TV) and major regional and national markets.',
  'VR headset forecast': 'Forecast for unit sales, installed base, and revenues for VR headsets. Split by device type (mobile VR, dedicated VR, promotional VR), use case (portable, home), and region.',
  'Wearables forecast': 'Forecast detailing installed base and revenues for consumer wearable devices. Split by device type (activity trackers, multipurpose devices, smart clothing and accessories), smartness index, and region.',
  'TV devices forecast': 'Forecast installed base, unit sales, and users for TV services split by country and device type.',
  'App ecosystems forecast': 'Global app store downloads and revenues, segmented by ecosystem (Apple App Store, Google Play, others) and by app type (games, nongaming apps).',
  'Cloud gaming forecast': 'Forecast and historical cloud gaming revenues, split into one-off purchase revenues and subscription revenues, covering three different scenarios.',
  'Digital consumer publishing forecast': 'Digital consumer publishing data and forecasts covering consumer and advertising spend for the book, newspaper, and magazine industries and includes a breakdown of print and digital spending for all segments.',
  'Esports forecast': 'Sizing esports’ market potential, this forecast provides revenue breakdowns by media rights, streaming advertising, sponsorship, ticket sales, and consumer contributions to tournament prize pots.',
  'Mobile games forecast': 'Global app store mobile games downloads and revenues, segmented by ecosystem (Apple App Store, Google Play, others) and by revenue type (end-user spend, in-app advertising).',
  'Video game revenue forecast': 'Forecast of video game revenues, split by traditional (PC, console) and nontraditional gaming (app-based gaming, browser-based gaming), region, and 67 national markets.',
  'VR content revenue forecast': 'Forecast sizing the market potential for content and apps developed for consumer VR devices. It provides content revenue breakdowns by type of VR headset, content type, and region.',
  'Carrier-billing forecast by billing type': 'Global carrier-billing revenues segmented by billing type, namely PSMS and direct carrier billing (DCB).',
  'Carrier-billing forecast by revenue share': 'Global carrier-billing revenues segmented by the share of revenues kept by communication service providers and the share kept by other value chain players.',
  'Carrier-billing forecast by segment': 'Global carrier-billing revenues segmented by OS app stores, indie stores, online PC games, browser-based, messaging-based (PRS), mobile bundling/off-store, consoles/STBs/others, and physical goods/services.',
  'Mobile payments forecast': 'Tracks users, transaction volumes, and total transaction value for key consumer mobile payment segments: B2C mobile commerce, mobile proximity payment (NFC, non-NFC), and P2P money transfer (domestic, international).',
  'Broadband bundle forecast': 'Forecast detailing subscription forecasts for single-play, dual-play, triple-play, quad-play, and other combinations of consumer broadband bundles across 67 countries and eight regions.',
  'Consumer fixed broadband forecast': 'Forecast detailing consumer fixed broadband subscriptions by access technology and by speed, household penetration, and service revenues generated, covering 67 countries and eight regions.',
  'Consumer fixed voice forecast': 'Forecast detailing consumer fixed voice connections, household penetration, and service revenues generated, covering 67 countries and eight regions.',
  'Consumer mobile forecast': 'Forecast detailing consumer mobile subscriptions and service revenues generated by voice and data services, covering 67 countries and eight regions.',
  'Telco TV forecast': 'Projected and historical global data for telco TV connections, OTT video connections, TV revenue, TV ARPU, and pay-TV subscriber market share, split by country.',
  'Fixed broadband forecast by speed': 'Forecast fixed broadband subscriptions split by connection speed.',
  'OTT SVOD subscriptions forecast': 'Forecast SVOD subscriptions split by country.',
  'Public service TV forecast': 'Forecast financial KPI for public service TV split by country.',
  'MVNO forecast': 'This forecast provides MVNO subscriptions, ARPU, and revenue forecasts for 67 named countries, seven rest-of regions, four regions, and seven subregions.',
  'Prepaid and postpaid mobile subscriptions': 'Forecasted subscriptions for mobile services by country and billing type (prepaid and postpaid).',
  'VoLTE subscription forecast': 'Subscriptions forecast for VoLTE services split by company & technology, covering 52 and the worlds major geographic regions. Also has VoLTE subscribers as a percentage of 4G & total subscriptions.',
  'Mobile data subscription forecast': 'Mobile data subscriptions split by company.',
  'Mobile M2M Subscriptions': 'Forecasted and historical subscriptions for M2M mobile services by company and technology.',
  'Mobile subscription forecast excluding M2M': 'Forecast and historical subscriptions for non-M2M mobile services split by company and technology.',
  'Global wholesale market forecast': 'Forecast of the value of the market for wholesale telecoms services globally, regionally, and for 25 countries. Includes revenue estimates for six major wholesale service groupings.',
  'Carrier Ethernet equipment forecast': 'Forecast covers projected annual equipment revenues by segment (carrier Ethernet switch/router, Ethernet access and aggregation, optical Ethernet transport, and packet radio).',
  'Cellular M2M forecast (Market level)': 'Forecast of country-level M2M connections and service revenue in 67 national markets along with rest-of region information to encompass all remaining countries.',
  'Cellular M2M forecast (Operator level)': 'Forecasts of the operator share of M2M revenue in 67 national markets along with rest-of region information to encompass all remaining countries.',
  'Cellular M2M forecast by industry': 'Split of M2M connections and service revenues forecast by major segments. Figures provided for eight regional markets.',
  'Cellular M2M forecast by service layer': 'Split of forecasted M2M service revenue by service layer: network, managed connectivity, application development, and integration. Figures provided for eight regional markets.',
  'Cloud services forecast by employee size': 'Forecast includes the delivery of software, infrastructure, compute, and storage over the internet or private wide area networks based on usage-based demand and split across enterprise size.',
  'Cloud services forecast by industry': 'Forecast includes the delivery of software, infrastructure, compute, and storage over the internet or private wide area networks based on usage-based demand and split across industries.',
  'Cloud services forecast by region': 'Forecast includes the delivery of software, infrastructure, compute, and storage over the internet or private wide area networks based on usage-based demand and split across SaaS, IaaS, and PaaS.',
  'Cloud services forecast by telco share': 'Forecast provides gross annuity revenues that CSPs generate from the resale of cloud services, including from IP Centrex and multitenant hosted UC services (which are categorized under SaaS).',
  'Communications Provider Revenues & Capex forecast': 'Forecast and historical data of revenue and capex of fixed and mobile CSPs (communications service providers or telcos), internet content providers, and carrier-neutral providers.',
  'Corporate banking technology by location': 'Forecast of technology spend by corporate banking institutions by location (back office, front office, middle office, and other) for 20 countries and four regions.',
  'Corporate banking technology by source': 'Forecast of technology spend by corporate banking institutions across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Corporate-liable forecast by company size': 'Forecast of business mobile subscriptions & the revenues attributed to the provision of services generated from these subscriptions. Forecast is divided into five company size categories & are provided for 67 countries.',
  'Corporate-liable voice/nonvoice revenues': 'Forecast of revenues attributed to the provision of services generated from business mobile subscriptions. Forecasts are divided into voice and nonvoice revenues and are provided for 67 countries.',
  'Digital assistant device forecast': 'Forecast and historical installed base for digital assistants by device segment and by vendor. Includes Google Assistant, Apple Siri, Amazon Alexa, Microsoft Cortana, Samsung Bixby, and Chinese assistants.',
  'Digital publishing transformation ICT services forecast': 'Encompasses digital transformation ICT services spend across three core publishing segments: newspaper, books, and periodicals.',
  'Employee-liable mobile connections forecast': 'Forecast of consumer mobile subscriptions where the devices are also used for business purposes. Forecasts are divided into two BYOD categories for 67 countries.',
  'Enterprise application forecast by cloud': 'Forecast provides revenue opportunity forecasts for cloud-based enterprise applications software market, spanning CRM, commerce, ERP, HCM, and SCM.',
  'Enterprise application forecast by industry': 'Forecast provides revenue opportunity estimates for the enterprise applications software market spanning seven subsegments, four regions, eight subregions, 20 countries, and 16 verticals.',
  'Enterprise application forecast by region': 'Forecast provides revenue opportunity estimates for the enterprise applications software market, spanning seven subsegments, four regions, eight subregions, 20 countries, and 16 verticals.',
  'Enterprise fixed broadband forecast': 'Forecast detailing enterprise fixed broadband subscriptions and service revenues generated, covering 67 countries and eight regions.',
  'Enterprise fixed voice forecast': 'Forecast detailing enterprise fixed voice connections and service revenues generated, covering 67 countries and eight regions.',
  'Enterprise mobility forecast by channel': 'Enterprise mobility management software spending forecast by channel to market.',
  'Enterprise mobility forecast by delivery': 'Enterprise mobility spending forecast by on-premises or SaaS delivery method.',
  'Enterprise mobility forecast by employee size': 'Enterprise mobility management software spending forecast by customer size based on the number of employees.',
  'Enterprise mobility forecast by industry': 'Enterprise mobility management software spending forecast by major industries.',
  'Enterprise mobility forecast by license type': 'Enterprise mobility spending forecast based on per-user or per-device license type.',
  'Enterprise mobility forecast by product category': 'Forecast provides revenue opportunity estimates for EMM software, a collection of tools that help organizations to manage and secure smart mobile devices and the corporate data or applications on it.',
  'Enterprise mobility forecast by region': 'Forecast provides enterprise mobility management software spending split by region.',
  'Financial markets technology forecast by cloud': 'Forecast of cloud spend by financial market institutions broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Financial markets technology forecast by location': 'Forecast of technology spend by financial market institutions broken by location for 20 countries and four regions.',
  'Financial markets technology forecast by source': 'Forecast of technology spend by financial market institutions across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Fixed broadband forecast': 'Forecast detailing fixed broadband subscriptions, penetration, and service revenues generated by access technology and covering 67 countries and eight regions.',
  'Fixed voice forecast': 'Forecast detailing fixed voice subscriptions by technology, service revenues, subscription revenues, and call revenues, covering 67 countries and eight regions.',
  'Government technology forecast by cloud': 'Forecast of cloud spend by government organizations broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Government technology forecast by source': 'Forecast of government technology spend across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Healthcare technology forecast by cloud': 'Forecast of cloud spend by healthcare organizations broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Healthcare technology forecast by function': 'Forecast of technology function spend by healthcare organizations across business intelligence & analytics, EHRs, patient administration, RCM, e-prescribing, and PACs for 20 countries and four regions.',
  'Healthcare technology forecast by source': 'Forecast of technology spend by healthcare organizations across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Higher education technology forecast by cloud': 'Forecast of cloud spend by higher education institutions broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Higher education technology forecast by function': 'Forecast of technology function spend by higher education institutions across SIS, ERP (HR and finance), LMS, and CRM for 20 countries and four regions.',
  'Higher education technology forecast by source': 'Forecast of technology spend by higher education institutions across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Hosted and managed unified communications services forecast': 'Forecast detailing revenues and seats for hosted and managed UC services split by country and region.',
  'Hosted and managed unified communications services forecast by size': 'Forecast detailing revenues for hosted and managed UC services split by country, region, and company size.',
  'Hosted and managed unified communications services forecast by vertical': 'Forecast detailing revenue for hosted and managed UC services split by country, region, and industry.',
  'Information management cloud forecast by industry': 'Forecast of spend on cloud-based information management solutions by enterprises in major industries.',
  'Information management cloud forecast by region': 'Forecast of spend on cloud-based information management solutions provided for eight subregions.',
  'Information management forecast by industry': 'Forecast of spend on information management solutions by enterprises in major industries.',
  'Information management forecast by region': 'Forecast of spend on five information management solutions: big data, BI & analytics, enterprise content management, data management, and enterprise performance management.',
  'Infrastructure software forecast by industry': 'Forecast provides revenue opportunity estimates for the infrastructure software market, spanning 11 subsegments and 16 verticals.',
  'Infrastructure software forecast by region': 'Forecast provides revenue opportunity estimates for the infrastructure software market, spanning 11 subsegments, four regions, eight subregions, and 20 countries.',
  'Insurance technology forecast by cloud': 'Forecast of cloud spend by insurance providers broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Insurance technology forecast by function': 'Forecast of technology spend by life insurance and non-life insurance providers split out by business functions and locations.',
  'Insurance technology forecast by location': 'Forecast of technology spend by life insurance and non-life insurance providers split out by location (back office, front office, middle office, and other) for 20 countries and four regions.',
  'Insurance technology forecast by source': 'Forecast of technology spend by life insurance and non-life insurance providers across infrastructure, applications, IT services, consulting, communications, and internal IT.',
  'Integration forecast by region': 'Forecast provides revenue opportunity estimates for the integration software (middleware) market, spanning six subsegments, four regions, and 21 countries.',
  'Intra–data center ports forecast': 'Forecast for intra–data center optical ports, segmented by optical intraconnect speed: 40G, 100G, and 400G. A leading ICP DC square footage projection is provided.',
  'IP VPN forecast': 'Forecast for enterprise IP VPN services. Connection forecasts are split by MPLS and IPSec-based VPNs. Revenue forecasts are split by enterprise size and industry vertical. Also forecasts proportion of IP VPN that is SDN managed.',
  'IT management forecast by industry': 'Forecast provides revenue opportunity estimates for the IT management software market, spanning three subsegments and 16 verticals.',
  'IT management forecast by region': 'Forecast provides revenue opportunity estimates for the IT management software market, spanning three subsegments and five regions.',
  'LTE by spectrum forecast': 'Forecast detailing the addressable market per band of LTE spectrum band adoption, including the LTE launch date for each spectrum band by country and operator.',
  'Media transformation ICT services forecast': 'Encompasses ICT services spend across five core premium media asset owner segments: broadcasters, cable TV, satellite TV, sports franchises, and telcos migrating to OTT services.',
  'Mobile AR forecast': 'Forecast and historical installed base of smartphones with augmented reality–enabling software installed on the device, split by market and operating system.',
  'Mobile backhaul & fronthaul – medium': 'Forecast for mobile backhaul & fronthaul equipment spending related to the type of connectivity used including fiber, wireless, and copper. Wireless would include microwave and millimeter wave solutions.',
  'Mobile backhaul & fronthaul – technology': 'Forecast for mobile backhaul equipment spending by underlying technology served (e.g., Ethernet and TDM)',
  'Mobile broadband forecast': 'Forecast detailing mobile and portable broadband device connections, covering 67 countries and eight regions.',
  'Mobile forecast': 'Forecast detailing mobile subscriptions and service revenues generated by voice data & SMS services. Includes Omdia\'s 5G forecast and M2M revenues and subscriptions and covers 67 countries and eight regions.',
  'Mobile forecast – M2M': 'Forecast detailing mobile subscriptions and service revenues generated for M2M services, covering 67 countries and eight regions.',
  'Mobile forecast – Non-M2M': 'Forecast detailing mobile subscriptions and service revenues generated for non-M2M services, covering 67 countries and eight regions.',
  'Mobile revenue forecast by billing type': 'Forecast and historical data of aggregate consumer mobile service and hardware revenues of mobile network operators from 2014 to 2021 split by billing type, covering 19 countries and eight regions.',
  'Mobile revenue forecast by sales channel': 'Forecast and historical data of aggregate consumer mobile service and hardware revenues of mobile network operators from 2014 to 2021 split by sales channels, covering 19 countries and eight regions.',
  'Mobile roaming forecast': 'Forecast detailing mobile roaming trips, traffic, and revenues generated, covering 19 countries and eight regions.',
  'Mobile, broadband, and pay-TV integrated forecast': 'Integrated market-level view of Omdia\'s mobile, fixed, and pay-TV forecasts, covering 67 countries and eight regions.',
  'Network function virtualization (NFV) technology forecast': 'Forecast for spending on NFV-based infrastructure (NFVI), software, and services in the telecoms industry.',
  'OC FTTx forecast': 'Forecast of transceivers/BOSAs used in FTTx PON. It covers OLT transceivers and ONT transceivers/BOSAs (includes ONU transceivers/BOSAs), segmented by different types of PON and tracks unit volumes, ASPs, and revenues.',
  'Optical network equipment forecast': 'Historical performance and forecast for optical network ports and common equipment. Revenues, ASPs, and port volumes are highlighted. Results are also provided by the major regions of world.',
  'OSS/BSS revenue forecast by business category': 'Forecast focuses on software-led or services-led OSS/BSS revenues that third parties, such as vendors, earn from CSPs (communications service providers or telcos).',
  'OSS/BSS revenue forecast by product category': 'Forecast focuses on product-led OSS/BSS revenues that third parties, such as vendors, earn from CSPs (communications service providers or telcos).',
  'OSS/BSS revenue forecast by region': 'Forecast focuses on revenues that third parties, such as vendors, earn from the OSS/BSS-related products and services that they provide to CSPs (communications service providers or telcos).',
  'Outsourcing, consulting, and systems integration forecast by industry': 'Forecast provides spend data for IT service lines namely consulting, systems integration, applications, infrastructure and BPO split by industry.',
  'Outsourcing, consulting, and systems integration forecast by region': 'Forecast provides spend data for IT service lines: consulting, systems integration, applications, infrastructure, and BPO split by country and regions.',
  'Payments technology forecast by function': 'Forecast of payments technology function spend across fraud, payment hubs, retail payments, wholesale payments, and real-time payments for 20 countries and four regions.',
  'Payments technology forecast by source': 'Forecast of payments technology spend across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Pay-TV leaders and telco TV forecast by service provider': 'Pay-TV and OTT video subscriber growth and market share projections for a given country\'s largest service providers, plus country-level projections for aggregated telco TV and OTT video connections, revenue, ARPU, and pay-TV subscriber market share.',
  'Podcast forecast': 'Forecast for all revenue generated from advertising carried within podcasts, whether directly embedded in the audio file or dynamically inserted, and the number of people who have listened to at least one podcast in the last month',
  'Radio access network forecast': 'Forecast for revenues coming from the sales of radio access networks. Revenue total includes macro cells, small cells, and radio controllers. Forecast segmented by regions and air interface.',
  'Retail banking technology forecast by cloud': 'Forecast of cloud spend by retail banking institutions broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Retail banking technology forecast by function': 'Forecast of retail banking technology spend by business functions such as back-office systems, operations, core systems, MIS, CIS, branch, call centers, online banking, ATMs, and mobile banking.',
  'Retail banking technology forecast by location': 'Forecast of retail banking technology spend broken by location for 20 countries and four regions.',
  'Retail banking technology forecast by source': 'Forecast of technology spend by retail banking institutions across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Retail technology forecast by cloud': 'Forecast of cloud spend by retail organizations broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Retail technology forecast by source': 'Forecast of technology spend by retail organizations across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'SDN service provider multilayer orchestration forecast ': 'Forecast for spending on software that automates and orchestrates transport, routing, and switching products.',
  'Smart home services forecast': 'Forecast detailing household penetration and revenue growth for key smart home markets, covering 20 countries and eight regions.',
  'Smartphone connections forecast': 'Forecast detailing smartphone connections, unique users, and penetration rates, covering 67 countries and eight regions.',
  'Software lifecycle management forecast by industry': 'Forecast provides revenue opportunity estimates for the software lifecycle management market, spanning four subsegments and 16 verticals.',
  'Software lifecycle management forecast by region': 'Forecast provides revenue opportunity estimates for the software lifecycle management market, spanning four subsegments, four regions, seven subregions, and 16 countries.',
  'Switching and routing forecast': 'Forecast for spending by service providers on core, edge, Ethernet, & access switching/routing devices along with their applications as SDN-controlled routers and virtualized routers.',
  'Switching and routing forecast – ports': 'Forecast for ports by unit deployed in service provider–focused core, edge, Ethernet, and access products split by type including 400G, 100G, 50G, 25G, 10G, 1G.',
  'Telco-managed ICT services forecast': 'Telco revenues from ICT services to large enterprises (1,000+ employees), with splits for legacy voice, data, and six types of strategic services for nine industry verticals and eight geographic regions.',
  'Telco-managed ICT services forecast by industry sector': 'Industry spend by vertical across six types of strategic ICT services supplied by telcos to large enterprises (at least 1,000 employees), including public sector, as multinational managed services.',
  'Telecoms IT forecast by cloud': 'Forecast of cloud spend in telecoms sector by IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Telecoms IT forecast by source': 'Forecast of IT spend in telecoms sector across infrastructure, applications, IT services, consulting, communications, and internal IT split out for 20 countries and four regions.',
  'Vendor telecoms services forecast by region': 'Vendor services forecast covering revenues that third parties such as vendors and professional services providers earn from the network and IT services that they provide to CSPs. Forecast by region.',
  'Vendor telecoms services forecast by segment': 'Vendor services forecast covering revenues that third parties, such as vendors and professional services providers, earn from the network and IT services that they provide to CSPs. Forecast by segment.',
  'Voice AI–capable device forecast': 'Forecast and historical unit sales and installed base for voice AI–capable smartphone, tablet, wearable, VR, smart home, and TV devices.',
  'VoLTE subscription forecast – World': 'Subscriptions forecast for VoLTE services split by company & technology at a global level. It also has VoLTE subscribers as a percentage of 4G & total subscriptions.',
  'Wealth management technology forecast by cloud': 'Forecast of cloud spend by wealth management institutions broken into IaaS, PaaS, and SaaS for 20 countries and four regions.',
  'Wealth management technology forecast by function': 'Forecast of technology spend by wealth management institutions by business lines split across business functions such as advisor, CIS, MIS, core systems, and operations.',
  'Wealth management technology forecast by location': 'Forecast of technology spend by wealth management institutions by business lines broken out by location for 20 countries and four regions.',
  'Wealth management technology forecast by source': 'Forecast of technology spend by wealth management institutions across infrastructure, applications, IT services, consulting, communications, and internal IT for 20 countries and four regions.',
  'Workforce optimization forecast by technology': 'Forecast provides revenue opportunity estimates for the workforce optimization technologies market in seven segments.',
  'Workforce optimization forecast by vertical': 'Forecast provides revenue opportunity estimates for the workforce optimization technologies market in major industries.',
  'Set-top box forecast by connectivity': 'Forecast and historical unit sales and installed base for connected digital STBs for major regional and national markets.',
  'Set-top box forecast by technology': 'Forecast and historical unit sales and installed base for 4K UHD digital STBs for major regional and national markets.',
  'Hosted & managed unified comms services': 'Forecast detailing revenues and seats for hosted and managed UC services split by country and region.',
  'Hosted & managed unified comms services by size': 'Forecast detailing revenues for hosted and managed UC services split by country, region, and company size.',
  'Hosted & managed unified comms services by vertical': 'Forecast detailing revenue for hosted and managed UC services split by country, region, and industry.',
  'IP VPN Forecast': 'Forecast for enterprise IP VPN services. Connection forecasts are split by MPLS and IPSec-based VPNs. Revenue forecasts are split by enterprise size and industry vertical. Also forecasts proportion of IP VPN that is SDN managed.',
  'Outsourcing, consulting & systems integration by industry': 'Forecast provides spend data for IT service lines namely consulting, systems integration, applications, infrastructure and BPO split by industry.',
  'Outsourcing, consulting & systems integration by region': 'Forecast provides spend data for IT service lines: consulting, systems integration, applications, infrastructure, and BPO split by country and regions.',
  'Telco-managed ICT services': 'Telco revenues from ICT services to large enterprises (1,000+ employees), with splits for legacy voice, data, and six types of strategic services for nine industry verticals and eight geographic regions.',
  'Telco-managed ICT services by industry sector': 'Industry spend by vertical across six types of strategic ICT services supplied by telcos to large enterprises (at least 1,000 employees), including public sector, as multinational managed services.',
  'IT security forecast by industry': 'Forecast provides revenue opportunity estimates for the enterprise IT security software market, spanning 17 subsegments and 16 verticals.',
  'IT security forecast by region': 'Forecast provides revenue opportunity estimates for the enterprise IT security software market, spanning 17 subsegments, four regions, and 20 countries.',
  'Outsourced & managed security services by industry': 'Forecast provides revenue opportunity estimates for the outsourced and managed security services market, spanning 16 verticals.',
  'Outsourced & managed security services by region': 'Forecast provides revenue opportunity estimates for the outsourced and managed security services market, spanning four regions and 20 countries.',
  'Core mobile services': 'Forecast and historical subscriptions for mobile services split by company and technology. Forecast and historical financial KPI split by country. Forecast mobile unique users split by country and mobile device sales split by country and technology.',
  'Mobile data and voice': 'Forecast and historical service revenues split by voice and data. Historical active data users and data traffic split by company.',
  'Data center interconnect forecast': 'Historical performance and forecast for the system vendors data center interconnect revenues by spender type (CSP, ICP, enterprise, and government) and by region.',
  'Recorded-music retail sales forecast': 'Forecast details spending on physical and digital formats and services. Also includes trade income from ad-supported free tiers of premium subscription services, services funded by advertising, performance rights, and synchronization earnings.',
  'Enterprise video logistics forecast': 'Forecast for the enterprise video logistics market covering seven major industries and seven applications segments. ',
  'Optical network application forecast': 'Historical revenue performance and forecast for optical network applications by key technologies. Results are also provided by major regions and key countries.',
  'Traffic forecast by network': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Average usage is calculated by dividing by cellular/wireless device installed base or households.',
  'Traffic forecast by device': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Devices covers smartphones, nonsmartphones, tablets, other portable, TV devices, and VR headsets.',
  'Traffic forecast by service': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Service categories are video, gaming, music, virtual reality, social networking, communications, and other.',
  'Traffic forecast by network and device': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Traffic is split by network and device (e.g., smartphone data traffic on a cellular network).',
  'Traffic forecast by network and service': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Traffic is split by network and service (e.g., video content viewed using a Wi-Fi connection).',
  'Traffic forecast by device and service': 'Forecast of data traffic on cellular plus consumer-generated uplink and downlink fixed broadband including Wi-Fi. Traffic is split by device and service (e.g., social networking traffic on a tablet device).'
};
